name: flutter_flexible_calendar
description: flutter_flexible_calendar lib allow to create standard calendar and horizontal calendar, just listen callback both events.
version: 1.0.1
homepage: https://github.com/kdrtech/flutter_flexible_calendar

environment:
  sdk: ^3.2.6

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  intl: ^0.19.0
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
